# Generated by Django 4.0.1 on 2022-02-11 21:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niramaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refernce',
            fields=[
                ('refernce_sno', models.AutoField(primary_key=True, serialize=False)),
                ('refernce_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('patient_info', models.FileField(upload_to='uploads/')),
                ('message', models.CharField(max_length=500)),
                ('refernce_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niramaya.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
