# Generated by Django 4.0.1 on 2022-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0002_refernce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refernce',
            old_name='patient_info',
            new_name='patientInfo',
        ),
        migrations.AddField(
            model_name='refernce',
            name='acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refernce',
            name='patientID',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='refernce',
            name='patientName',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
