# Generated by Django 4.0.1 on 2022-02-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0003_rename_patient_info_refernce_patientinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refernce',
            name='acceptance',
        ),
    ]
