# Generated by Django 4.0.1 on 2022-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0004_remove_refernce_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='refernce',
            name='acceptance',
            field=models.CharField(choices=[(1, 'Waiting'), (2, 'Accepted'), (3, 'Rejected')], default=1, max_length=2),
        ),
    ]
