# Generated by Django 4.0.1 on 2022-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0005_refernce_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Level',
            field=models.IntegerField(default=0),
        ),
    ]
