# Generated by Django 4.0.1 on 2022-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0007_alter_hospital_bic_units_alter_hospital_cic_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='serial',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
