# Generated by Django 4.0.1 on 2022-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0008_alter_hospital_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refernce',
            name='patientInfo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
