# Generated by Django 4.0.1 on 2022-02-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0011_alter_refernce_patientid_alter_refernce_patientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refernce',
            name='patientID',
            field=models.CharField(max_length=20),
        ),
    ]
