# Generated by Django 4.0.1 on 2022-02-13 09:38

from django.db import migrations, models
import niramaya.models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0012_alter_refernce_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refernce',
            name='patientInfo',
            field=models.FileField(blank=True, null=True, upload_to=niramaya.models.get_path),
        ),
    ]
