# Generated by Django 4.0.1 on 2022-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0015_alter_refernce_acceptance_alter_refernce_patientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refernce',
            name='acceptance',
            field=models.CharField(choices=[('1', 'Waiting'), ('2', 'Accepted'), ('3', 'Rejected')], default=1, max_length=2),
        ),
    ]
