# Generated by Django 4.0.1 on 2022-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0016_alter_refernce_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='TIC_units',
            field=models.BooleanField(default=False),
        ),
    ]
