# Generated by Django 4.0.1 on 2022-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0018_alter_hospital_tic_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='CIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TIC_units',
            field=models.BooleanField(default=False),
        ),
    ]
