# Generated by Django 4.0.1 on 2022-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niramaya', '0019_alter_hospital_cic_units_alter_hospital_tic_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='BIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_cath',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_electro',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_intervene',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_rehab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_stenting',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_surgery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_vas_interv',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='C_vas_surg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='DIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='EME_TC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='EME_dept',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='EME_ped_TC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ICU_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_chem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_cyto',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_hemo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_immuno',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_microB',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_surg_path',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Lab_trans',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='NIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='N_EEG',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='N_sleep',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Nursery_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='On_chemo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='On_rad',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_heart',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_intestinal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_kidney',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_liver',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_lung',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Or_pancreas',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='PeIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='PrIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='PsIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_com_T',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_com_TA',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_IMRT',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_MRA',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_MRI',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_PET',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_SPECT',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='R_dig_mamo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Re_phy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Re_sp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='SIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_BICU',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_CCU',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_ICU',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_NIC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_PeIC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_PrIC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_PsIC',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_SICU',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_TCU',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Sp_det',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TIC_units',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='av_gen_bed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='av_spec_bed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='av_surg_bed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ortho_Arth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ortho_JR',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ortho_spine',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
